server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: #数组形式
      - id: order-service #路路由唯一一标识
        uri: http://127.0.0.1:8000 #uri: http://127.0.0.1:8000想要转发到的地址
    #从nacos获取名称转发,lb是负载均衡轮训策略略
        predicates: #断言 配置哪个路路径才转发
          - Path=/order-server/**
        filters: #过滤器,请求在传递过程中通过滤器器修改
          - StripPrefix=1 #去掉第一一层前缀
## 访问路路径 http://localhost:8888/order-server/api/v1/video_order/list
## transfer location http://localhost:8000/order-server/api/v1/video_order/list


  #开启网网关拉取nacos的服
      - id: book-service #another gateway
          uri: lb://xdclass-order-service #uri: http://127.0.0.1:8000想要转发到的地址
          #从nacos获取名称转发,lb是负载均衡轮训策略略
          predicates: #断言言 配置哪个路路径才转发
            - Path=/order-server/**
          filters: #过滤器器,请求在传递过程中通过过滤器器修改
            - StripPrefix=1 #去掉第一一层前缀